name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install pygments
      run: pip3 install pygments
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
